#pragma once

enum Socks5RequestCode {
	SOCKS5_ESTABLISH_CONNECTION_COMMAND_CODE = 0x01,
	RESERVED_BYTE = 0x00,
	SOCKS5_VERSION = 0x05,
	SOCKS5_AUTH_METHOD_NO_AUTH = 0x00,
	IPV4_VERSION = 0x01,
	DOMAIN_NAME = 0x03,
	
};

enum Socks5RequestSize {
	IPV4_ADDRESS_SIZE = 4,
	MAX_INIT_REQUEST = 258,
	MIN_GREETING_SIZE = 3,
	MIN_REQUEST_SIZE = 10
};

enum Socks5RequestIndex {
	VERSION_INDEX = 0,
	RESPONSE_CODE_INDEX = 1,
	REQUEST_COMMAND_CODE_INDEX = 1,
	RESERVED_BYTE_INDEX = 2,
	ADDRESS_TYPE_INDEX = 3,
	BEGIN_ADDRESS_INDEX = 4
};


enum Socks5ResponseCode {
	SUCCESS = 0x00,
	SERVER_EXCEPTION = 0x01,
	HOST_UNAVAILABLE = 0x04,
	CONNECTION_REJECTION = 0x05,
	INVALID_COMMAND_TYPE = 0x07,
	INVALID_ADDRESS = 0x08
};